import { League, Team } from './types';

export const LEAGUES: League[] = [
  {
    id: 'nhl',
    name: 'National Hockey League',
    shortName: 'NHL',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3a/05_NHL_Shield.svg/200px-05_NHL_Shield.svg.png',
  },
  {
    id: 'nba',
    name: 'National Basketball Association',
    shortName: 'NBA',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/03/National_Basketball_Association_logo.svg/200px-National_Basketball_Association_logo.svg.png',
  },
  {
    id: 'nfl',
    name: 'National Football League',
    shortName: 'NFL',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/National_Football_League_logo.svg/200px-National_Football_League_logo.svg.png',
  },
  {
    id: 'mlb',
    name: 'Major League Baseball',
    shortName: 'MLB',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Major_League_Baseball_logo.svg/200px-Major_League_Baseball_logo.svg.png',
  },
  {
    id: 'mls',
    name: 'Major League Soccer',
    shortName: 'MLS',
    logoUrl: 'https://a.espncdn.com/i/leaguelogos/soccer/500/19.png',
  },
];

export const NHL_TEAMS: Team[] = [
  { id: 'ana', name: 'Anaheim Ducks', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/ana.png', primaryColor: '#F47A38', secondaryColor: '#B9975B', city: 'Anaheim', abbreviation: 'ANA' },
  { id: 'ari', name: 'Utah Mammoth', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/uta.png', primaryColor: '#69B3E7', secondaryColor: '#010101', city: 'Salt Lake City', abbreviation: 'UTA' },
  { id: 'bos', name: 'Boston Bruins', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/bos.png', primaryColor: '#FFB81C', secondaryColor: '#000000', city: 'Boston', abbreviation: 'BOS' },
  { id: 'buf', name: 'Buffalo Sabres', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/buf.png', primaryColor: '#002654', secondaryColor: '#FCB514', city: 'Buffalo', abbreviation: 'BUF' },
  { id: 'cgy', name: 'Calgary Flames', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/cgy.png', primaryColor: '#C8102E', secondaryColor: '#F1BE48', city: 'Calgary', abbreviation: 'CGY' },
  { id: 'car', name: 'Carolina Hurricanes', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/car.png', primaryColor: '#CC0000', secondaryColor: '#000000', city: 'Raleigh', abbreviation: 'CAR' },
  { id: 'chi', name: 'Chicago Blackhawks', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/chi.png', primaryColor: '#CF0A2C', secondaryColor: '#000000', city: 'Chicago', abbreviation: 'CHI' },
  { id: 'col', name: 'Colorado Avalanche', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/col.png', primaryColor: '#6F263D', secondaryColor: '#236192', city: 'Denver', abbreviation: 'COL' },
  { id: 'cbj', name: 'Columbus Blue Jackets', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/cbj.png', primaryColor: '#002654', secondaryColor: '#CE1126', city: 'Columbus', abbreviation: 'CBJ' },
  { id: 'dal', name: 'Dallas Stars', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/dal.png', primaryColor: '#006847', secondaryColor: '#8F8F8C', city: 'Dallas', abbreviation: 'DAL' },
  { id: 'det', name: 'Detroit Red Wings', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/det.png', primaryColor: '#CE1126', secondaryColor: '#FFFFFF', city: 'Detroit', abbreviation: 'DET' },
  { id: 'edm', name: 'Edmonton Oilers', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/edm.png', primaryColor: '#041E42', secondaryColor: '#FF4C00', city: 'Edmonton', abbreviation: 'EDM' },
  { id: 'fla', name: 'Florida Panthers', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/fla.png', primaryColor: '#002B5C', secondaryColor: '#B9975B', city: 'Sunrise', abbreviation: 'FLA' },
  { id: 'lak', name: 'Los Angeles Kings', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/la.png', primaryColor: '#111111', secondaryColor: '#A2AAAD', city: 'Los Angeles', abbreviation: 'LAK' },
  { id: 'min', name: 'Minnesota Wild', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/min.png', primaryColor: '#154734', secondaryColor: '#A6192E', city: 'Saint Paul', abbreviation: 'MIN' },
  { id: 'mtl', name: 'Montreal Canadiens', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/mtl.png', primaryColor: '#AF1E2D', secondaryColor: '#192168', city: 'Montreal', abbreviation: 'MTL' },
  { id: 'nsh', name: 'Nashville Predators', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/nsh.png', primaryColor: '#FFB81C', secondaryColor: '#041E42', city: 'Nashville', abbreviation: 'NSH' },
  { id: 'njd', name: 'New Jersey Devils', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/njd.png', primaryColor: '#CE1126', secondaryColor: '#000000', city: 'Newark', abbreviation: 'NJD' },
  { id: 'nyi', name: 'New York Islanders', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/nyi.png', primaryColor: '#00539B', secondaryColor: '#F47D30', city: 'Elmont', abbreviation: 'NYI' },
  { id: 'nyr', name: 'New York Rangers', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/nyr.png', primaryColor: '#0038A8', secondaryColor: '#CE1126', city: 'New York', abbreviation: 'NYR' },
  { id: 'ott', name: 'Ottawa Senators', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/ott.png', primaryColor: '#C52032', secondaryColor: '#C69214', city: 'Ottawa', abbreviation: 'OTT' },
  { id: 'phi', name: 'Philadelphia Flyers', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/phi.png', primaryColor: '#F74902', secondaryColor: '#000000', city: 'Philadelphia', abbreviation: 'PHI' },
  { id: 'pit', name: 'Pittsburgh Penguins', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/pit.png', primaryColor: '#000000', secondaryColor: '#FCB514', city: 'Pittsburgh', abbreviation: 'PIT' },
  { id: 'sjs', name: 'San Jose Sharks', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/sj.png', primaryColor: '#006D75', secondaryColor: '#EA7200', city: 'San Jose', abbreviation: 'SJS' },
  { id: 'sea', name: 'Seattle Kraken', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/sea.png', primaryColor: '#001628', secondaryColor: '#99D9D9', city: 'Seattle', abbreviation: 'SEA' },
  { id: 'stl', name: 'St. Louis Blues', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/stl.png', primaryColor: '#002F87', secondaryColor: '#FCB514', city: 'St. Louis', abbreviation: 'STL' },
  { id: 'tbl', name: 'Tampa Bay Lightning', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/tb.png', primaryColor: '#002868', secondaryColor: '#FFFFFF', city: 'Tampa', abbreviation: 'TBL' },
  { id: 'tor', name: 'Toronto Maple Leafs', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/tor.png', primaryColor: '#00205B', secondaryColor: '#FFFFFF', city: 'Toronto', abbreviation: 'TOR' },
  { id: 'van', name: 'Vancouver Canucks', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/van.png', primaryColor: '#00205B', secondaryColor: '#00843D', city: 'Vancouver', abbreviation: 'VAN' },
  { id: 'vgk', name: 'Vegas Golden Knights', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/vgk.png', primaryColor: '#B4975A', secondaryColor: '#333F42', city: 'Las Vegas', abbreviation: 'VGK' },
  { id: 'wsh', name: 'Washington Capitals', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/wsh.png', primaryColor: '#041E42', secondaryColor: '#C8102E', city: 'Washington', abbreviation: 'WSH' },
  { id: 'wpg', name: 'Winnipeg Jets', leagueId: 'nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/wpg.png', primaryColor: '#041E42', secondaryColor: '#004C97', city: 'Winnipeg', abbreviation: 'WPG' },
];

export const NBA_TEAMS: Team[] = [
  { id: 'atl', name: 'Atlanta Hawks', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/24/Atlanta_Hawks_logo.svg/200px-Atlanta_Hawks_logo.svg.png', primaryColor: '#E03A3E', secondaryColor: '#C1D32F', city: 'Atlanta', abbreviation: 'ATL' },
  { id: 'bos-nba', name: 'Boston Celtics', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8f/Boston_Celtics.svg/200px-Boston_Celtics.svg.png', primaryColor: '#007A33', secondaryColor: '#BA9653', city: 'Boston', abbreviation: 'BOS' },
  { id: 'bkn', name: 'Brooklyn Nets', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Brooklyn_Nets_newlogo.svg/200px-Brooklyn_Nets_newlogo.svg.png', primaryColor: '#000000', secondaryColor: '#FFFFFF', city: 'Brooklyn', abbreviation: 'BKN' },
  { id: 'cha', name: 'Charlotte Hornets', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c4/Charlotte_Hornets_%282014%29.svg/200px-Charlotte_Hornets_%282014%29.svg.png', primaryColor: '#1D1160', secondaryColor: '#00788C', city: 'Charlotte', abbreviation: 'CHA' },
  { id: 'chi-nba', name: 'Chicago Bulls', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/67/Chicago_Bulls_logo.svg/200px-Chicago_Bulls_logo.svg.png', primaryColor: '#CE1141', secondaryColor: '#000000', city: 'Chicago', abbreviation: 'CHI' },
  { id: 'cle', name: 'Cleveland Cavaliers', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Cleveland_Cavaliers_logo.svg/200px-Cleveland_Cavaliers_logo.svg.png', primaryColor: '#860038', secondaryColor: '#FDBB30', city: 'Cleveland', abbreviation: 'CLE' },
  { id: 'dal-nba', name: 'Dallas Mavericks', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/97/Dallas_Mavericks_logo.svg/200px-Dallas_Mavericks_logo.svg.png', primaryColor: '#00538C', secondaryColor: '#002B5E', city: 'Dallas', abbreviation: 'DAL' },
  { id: 'den', name: 'Denver Nuggets', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/76/Denver_Nuggets.svg/200px-Denver_Nuggets.svg.png', primaryColor: '#0E2240', secondaryColor: '#FEC524', city: 'Denver', abbreviation: 'DEN' },
  { id: 'det-nba', name: 'Detroit Pistons', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Logo_of_the_Detroit_Pistons.svg/200px-Logo_of_the_Detroit_Pistons.svg.png', primaryColor: '#C8102E', secondaryColor: '#1D42BA', city: 'Detroit', abbreviation: 'DET' },
  { id: 'gsw', name: 'Golden State Warriors', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/01/Golden_State_Warriors_logo.svg/200px-Golden_State_Warriors_logo.svg.png', primaryColor: '#1D428A', secondaryColor: '#FFC72C', city: 'San Francisco', abbreviation: 'GS' },
  { id: 'hou', name: 'Houston Rockets', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/28/Houston_Rockets.svg/200px-Houston_Rockets.svg.png', primaryColor: '#CE1141', secondaryColor: '#000000', city: 'Houston', abbreviation: 'HOU' },
  { id: 'ind', name: 'Indiana Pacers', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/1b/Indiana_Pacers.svg/200px-Indiana_Pacers.svg.png', primaryColor: '#002D62', secondaryColor: '#FDBB30', city: 'Indianapolis', abbreviation: 'IND' },
  { id: 'lac', name: 'Los Angeles Clippers', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/ed/Los_Angeles_Clippers_%282024%29.svg/200px-Los_Angeles_Clippers_%282024%29.svg.png', primaryColor: '#C8102E', secondaryColor: '#1D428A', city: 'Los Angeles', abbreviation: 'LAC' },
  { id: 'lal', name: 'Los Angeles Lakers', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Los_Angeles_Lakers_logo.svg/200px-Los_Angeles_Lakers_logo.svg.png', primaryColor: '#552583', secondaryColor: '#FDB927', city: 'Los Angeles', abbreviation: 'LAL' },
  { id: 'mem', name: 'Memphis Grizzlies', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Memphis_Grizzlies.svg/200px-Memphis_Grizzlies.svg.png', primaryColor: '#5D76A9', secondaryColor: '#12173F', city: 'Memphis', abbreviation: 'MEM' },
  { id: 'mia', name: 'Miami Heat', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Miami_Heat_logo.svg/200px-Miami_Heat_logo.svg.png', primaryColor: '#98002E', secondaryColor: '#F9A01B', city: 'Miami', abbreviation: 'MIA' },
  { id: 'mil', name: 'Milwaukee Bucks', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4a/Milwaukee_Bucks_logo.svg/200px-Milwaukee_Bucks_logo.svg.png', primaryColor: '#00471B', secondaryColor: '#EEE1C6', city: 'Milwaukee', abbreviation: 'MIL' },
  { id: 'min-nba', name: 'Minnesota Timberwolves', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/Minnesota_Timberwolves_logo.svg/200px-Minnesota_Timberwolves_logo.svg.png', primaryColor: '#0C2340', secondaryColor: '#236192', city: 'Minneapolis', abbreviation: 'MIN' },
  { id: 'nop', name: 'New Orleans Pelicans', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0d/New_Orleans_Pelicans_logo.svg/200px-New_Orleans_Pelicans_logo.svg.png', primaryColor: '#0C2340', secondaryColor: '#C8102E', city: 'New Orleans', abbreviation: 'NOP' },
  { id: 'nyk', name: 'New York Knicks', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/25/New_York_Knicks_logo.svg/200px-New_York_Knicks_logo.svg.png', primaryColor: '#006BB6', secondaryColor: '#F58426', city: 'New York', abbreviation: 'NYK' },
  { id: 'okc', name: 'Oklahoma City Thunder', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5d/Oklahoma_City_Thunder.svg/200px-Oklahoma_City_Thunder.svg.png', primaryColor: '#007AC1', secondaryColor: '#EF3B24', city: 'Oklahoma City', abbreviation: 'OKC' },
  { id: 'orl', name: 'Orlando Magic', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/10/Orlando_Magic_logo.svg/200px-Orlando_Magic_logo.svg.png', primaryColor: '#0077C0', secondaryColor: '#C4CED4', city: 'Orlando', abbreviation: 'ORL' },
  { id: 'phi-nba', name: 'Philadelphia 76ers', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0e/Philadelphia_76ers_logo.svg/200px-Philadelphia_76ers_logo.svg.png', primaryColor: '#006BB6', secondaryColor: '#ED174C', city: 'Philadelphia', abbreviation: 'PHI' },
  { id: 'phx', name: 'Phoenix Suns', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/dc/Phoenix_Suns_logo.svg/200px-Phoenix_Suns_logo.svg.png', primaryColor: '#1D1160', secondaryColor: '#E56020', city: 'Phoenix', abbreviation: 'PHX' },
  { id: 'por', name: 'Portland Trail Blazers', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/21/Portland_Trail_Blazers_logo.svg/200px-Portland_Trail_Blazers_logo.svg.png', primaryColor: '#E03A3E', secondaryColor: '#000000', city: 'Portland', abbreviation: 'POR' },
  { id: 'sac', name: 'Sacramento Kings', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c7/SaijaxcramentoKings.svg/200px-SacramentoKings.svg.png', primaryColor: '#5A2D81', secondaryColor: '#63727A', city: 'Sacramento', abbreviation: 'SAC' },
  { id: 'sas', name: 'San Antonio Spurs', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/San_Antonio_Spurs.svg/200px-San_Antonio_Spurs.svg.png', primaryColor: '#C4CED4', secondaryColor: '#000000', city: 'San Antonio', abbreviation: 'SAS' },
  { id: 'tor-nba', name: 'Toronto Raptors', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/36/Toronto_Raptors_logo.svg/200px-Toronto_Raptors_logo.svg.png', primaryColor: '#CE1141', secondaryColor: '#000000', city: 'Toronto', abbreviation: 'TOR' },
  { id: 'uta', name: 'Utah Jazz', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/52/Utah_Jazz_logo_2022.svg/200px-Utah_Jazz_logo_2022.svg.png', primaryColor: '#002B5C', secondaryColor: '#00471B', city: 'Salt Lake City', abbreviation: 'UTA' },
  { id: 'was', name: 'Washington Wizards', leagueId: 'nba', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/02/Washington_Wizards_logo.svg/200px-Washington_Wizards_logo.svg.png', primaryColor: '#002B5C', secondaryColor: '#E31837', city: 'Washington', abbreviation: 'WAS' },
];

export const NFL_TEAMS: Team[] = [
  { id: 'ari-nfl', name: 'Arizona Cardinals', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/ari.png', primaryColor: '#97233F', secondaryColor: '#000000', city: 'Glendale', abbreviation: 'ARI' },
  { id: 'atl-nfl', name: 'Atlanta Falcons', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/atl.png', primaryColor: '#A71930', secondaryColor: '#000000', city: 'Atlanta', abbreviation: 'ATL' },
  { id: 'bal', name: 'Baltimore Ravens', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/bal.png', primaryColor: '#241773', secondaryColor: '#9E7C0C', city: 'Baltimore', abbreviation: 'BAL' },
  { id: 'buf-nfl', name: 'Buffalo Bills', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/buf.png', primaryColor: '#00338D', secondaryColor: '#C60C30', city: 'Orchard Park', abbreviation: 'BUF' },
  { id: 'car-nfl', name: 'Carolina Panthers', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/car.png', primaryColor: '#0085CA', secondaryColor: '#101820', city: 'Charlotte', abbreviation: 'CAR' },
  { id: 'chi-nfl', name: 'Chicago Bears', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/chi.png', primaryColor: '#0B162A', secondaryColor: '#C83803', city: 'Chicago', abbreviation: 'CHI' },
  { id: 'cin', name: 'Cincinnati Bengals', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/cin.png', primaryColor: '#FB4F14', secondaryColor: '#000000', city: 'Cincinnati', abbreviation: 'CIN' },
  { id: 'cle-nfl', name: 'Cleveland Browns', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/cle.png', primaryColor: '#311D00', secondaryColor: '#FF3C00', city: 'Cleveland', abbreviation: 'CLE' },
  { id: 'dal-nfl', name: 'Dallas Cowboys', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/dal.png', primaryColor: '#003594', secondaryColor: '#869397', city: 'Arlington', abbreviation: 'DAL' },
  { id: 'den-nfl', name: 'Denver Broncos', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/den.png', primaryColor: '#FB4F14', secondaryColor: '#002244', city: 'Denver', abbreviation: 'DEN' },
  { id: 'det-nfl', name: 'Detroit Lions', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/det.png', primaryColor: '#0076B6', secondaryColor: '#B0B7BC', city: 'Detroit', abbreviation: 'DET' },
  { id: 'gb', name: 'Green Bay Packers', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/gb.png', primaryColor: '#203731', secondaryColor: '#FFB612', city: 'Green Bay', abbreviation: 'GB' },
  { id: 'hou-nfl', name: 'Houston Texans', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/hou.png', primaryColor: '#03202F', secondaryColor: '#A71930', city: 'Houston', abbreviation: 'HOU' },
  { id: 'ind-nfl', name: 'Indianapolis Colts', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png', primaryColor: '#002C5F', secondaryColor: '#A2AAAD', city: 'Indianapolis', abbreviation: 'IND' },
  { id: 'jax', name: 'Jacksonville Jaguars', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/jax.png', primaryColor: '#101820', secondaryColor: '#D7A22A', city: 'Jacksonville', abbreviation: 'JAX' },
  { id: 'kc', name: 'Kansas City Chiefs', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/kc.png', primaryColor: '#E31837', secondaryColor: '#FFB81C', city: 'Kansas City', abbreviation: 'KC' },
  { id: 'lv', name: 'Las Vegas Raiders', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/lv.png', primaryColor: '#000000', secondaryColor: '#A5ACAF', city: 'Las Vegas', abbreviation: 'LV' },
  { id: 'lac-nfl', name: 'Los Angeles Chargers', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/lac.png', primaryColor: '#0080C6', secondaryColor: '#FFC20E', city: 'Inglewood', abbreviation: 'LAC' },
  { id: 'lar', name: 'Los Angeles Rams', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/lar.png', primaryColor: '#003594', secondaryColor: '#FFA300', city: 'Inglewood', abbreviation: 'LAR' },
  { id: 'mia-nfl', name: 'Miami Dolphins', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/mia.png', primaryColor: '#008E97', secondaryColor: '#FC4C02', city: 'Miami Gardens', abbreviation: 'MIA' },
  { id: 'min-nfl', name: 'Minnesota Vikings', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/min.png', primaryColor: '#4F2683', secondaryColor: '#FFC62F', city: 'Minneapolis', abbreviation: 'MIN' },
  { id: 'ne', name: 'New England Patriots', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/ne.png', primaryColor: '#002244', secondaryColor: '#C60C30', city: 'Foxborough', abbreviation: 'NE' },
  { id: 'no', name: 'New Orleans Saints', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/no.png', primaryColor: '#D3BC8D', secondaryColor: '#101820', city: 'New Orleans', abbreviation: 'NO' },
  { id: 'nyg', name: 'New York Giants', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png', primaryColor: '#0B2265', secondaryColor: '#A71930', city: 'East Rutherford', abbreviation: 'NYG' },
  { id: 'nyj', name: 'New York Jets', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png', primaryColor: '#125740', secondaryColor: '#000000', city: 'East Rutherford', abbreviation: 'NYJ' },
  { id: 'phi-nfl', name: 'Philadelphia Eagles', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/phi.png', primaryColor: '#004C54', secondaryColor: '#A5ACAF', city: 'Philadelphia', abbreviation: 'PHI' },
  { id: 'pit-nfl', name: 'Pittsburgh Steelers', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/pit.png', primaryColor: '#FFB612', secondaryColor: '#101820', city: 'Pittsburgh', abbreviation: 'PIT' },
  { id: 'sf', name: 'San Francisco 49ers', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/sf.png', primaryColor: '#AA0000', secondaryColor: '#B3995D', city: 'Santa Clara', abbreviation: 'SF' },
  { id: 'sea-nfl', name: 'Seattle Seahawks', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/sea.png', primaryColor: '#002244', secondaryColor: '#69BE28', city: 'Seattle', abbreviation: 'SEA' },
  { id: 'tb', name: 'Tampa Bay Buccaneers', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/tb.png', primaryColor: '#D50A0A', secondaryColor: '#FF7900', city: 'Tampa', abbreviation: 'TB' },
  { id: 'ten', name: 'Tennessee Titans', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/ten.png', primaryColor: '#0C2340', secondaryColor: '#4B92DB', city: 'Nashville', abbreviation: 'TEN' },
  { id: 'was-nfl', name: 'Washington Commanders', leagueId: 'nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png', primaryColor: '#5A1414', secondaryColor: '#FFB612', city: 'Landover', abbreviation: 'WAS' },
];

export const MLB_TEAMS: Team[] = [
  { id: 'ari-mlb', name: 'Arizona Diamondbacks', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/ari.png', primaryColor: '#A71930', secondaryColor: '#E3D4AD', city: 'Phoenix', abbreviation: 'ARI' },
  { id: 'atl-mlb', name: 'Atlanta Braves', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/atl.png', primaryColor: '#CE1141', secondaryColor: '#13274F', city: 'Atlanta', abbreviation: 'ATL' },
  { id: 'bal-mlb', name: 'Baltimore Orioles', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/bal.png', primaryColor: '#DF4601', secondaryColor: '#000000', city: 'Baltimore', abbreviation: 'BAL' },
  { id: 'bos-mlb', name: 'Boston Red Sox', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/bos.png', primaryColor: '#BD3039', secondaryColor: '#0C2340', city: 'Boston', abbreviation: 'BOS' },
  { id: 'chc', name: 'Chicago Cubs', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/chc.png', primaryColor: '#0E3386', secondaryColor: '#CC3433', city: 'Chicago', abbreviation: 'CHC' },
  { id: 'chw', name: 'Chicago White Sox', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/chw.png', primaryColor: '#27251F', secondaryColor: '#C4CED4', city: 'Chicago', abbreviation: 'CHW' },
  { id: 'cin-mlb', name: 'Cincinnati Reds', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/cin.png', primaryColor: '#C6011F', secondaryColor: '#000000', city: 'Cincinnati', abbreviation: 'CIN' },
  { id: 'cle-mlb', name: 'Cleveland Guardians', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/cle.png', primaryColor: '#00385D', secondaryColor: '#E50022', city: 'Cleveland', abbreviation: 'CLE' },
  { id: 'col-mlb', name: 'Colorado Rockies', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/col.png', primaryColor: '#33006F', secondaryColor: '#C4CED4', city: 'Denver', abbreviation: 'COL' },
  { id: 'det-mlb', name: 'Detroit Tigers', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/det.png', primaryColor: '#0C2340', secondaryColor: '#FA4616', city: 'Detroit', abbreviation: 'DET' },
  { id: 'hou-mlb', name: 'Houston Astros', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/hou.png', primaryColor: '#002D62', secondaryColor: '#EB6E1F', city: 'Houston', abbreviation: 'HOU' },
  { id: 'kc-mlb', name: 'Kansas City Royals', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/kc.png', primaryColor: '#004687', secondaryColor: '#BD9B60', city: 'Kansas City', abbreviation: 'KC' },
  { id: 'laa', name: 'Los Angeles Angels', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/laa.png', primaryColor: '#BA0021', secondaryColor: '#003263', city: 'Anaheim', abbreviation: 'LAA' },
  { id: 'lad', name: 'Los Angeles Dodgers', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/lad.png', primaryColor: '#005A9C', secondaryColor: '#EF3E42', city: 'Los Angeles', abbreviation: 'LAD' },
  { id: 'mia-mlb', name: 'Miami Marlins', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/mia.png', primaryColor: '#00A3E0', secondaryColor: '#EF3340', city: 'Miami', abbreviation: 'MIA' },
  { id: 'mil-mlb', name: 'Milwaukee Brewers', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/mil.png', primaryColor: '#12284B', secondaryColor: '#B6922E', city: 'Milwaukee', abbreviation: 'MIL' },
  { id: 'min-mlb', name: 'Minnesota Twins', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/min.png', primaryColor: '#002B5C', secondaryColor: '#D31145', city: 'Minneapolis', abbreviation: 'MIN' },
  { id: 'nym', name: 'New York Mets', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/nym.png', primaryColor: '#002D72', secondaryColor: '#FF5910', city: 'New York', abbreviation: 'NYM' },
  { id: 'nyy', name: 'New York Yankees', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/nyy.png', primaryColor: '#003087', secondaryColor: '#E4002C', city: 'New York', abbreviation: 'NYY' },
  { id: 'oak', name: 'Athletics', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/ath.png', primaryColor: '#003831', secondaryColor: '#EFB21E', city: 'Sacramento', abbreviation: 'ATH' },
  { id: 'phi-mlb', name: 'Philadelphia Phillies', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/phi.png', primaryColor: '#E81828', secondaryColor: '#002D72', city: 'Philadelphia', abbreviation: 'PHI' },
  { id: 'pit-mlb', name: 'Pittsburgh Pirates', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/pit.png', primaryColor: '#27251F', secondaryColor: '#FDB827', city: 'Pittsburgh', abbreviation: 'PIT' },
  { id: 'sd', name: 'San Diego Padres', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/sd.png', primaryColor: '#2F241D', secondaryColor: '#FFC425', city: 'San Diego', abbreviation: 'SD' },
  { id: 'sf-mlb', name: 'San Francisco Giants', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/sf.png', primaryColor: '#FD5A1E', secondaryColor: '#27251F', city: 'San Francisco', abbreviation: 'SF' },
  { id: 'sea-mlb', name: 'Seattle Mariners', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/sea.png', primaryColor: '#0C2C56', secondaryColor: '#005C5C', city: 'Seattle', abbreviation: 'SEA' },
  { id: 'stl-mlb', name: 'St. Louis Cardinals', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/stl.png', primaryColor: '#C41E3A', secondaryColor: '#0C2340', city: 'St. Louis', abbreviation: 'STL' },
  { id: 'tb-mlb', name: 'Tampa Bay Rays', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/tb.png', primaryColor: '#092C5C', secondaryColor: '#8FBCE6', city: 'St. Petersburg', abbreviation: 'TB' },
  { id: 'tex', name: 'Texas Rangers', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/tex.png', primaryColor: '#003278', secondaryColor: '#C0111F', city: 'Arlington', abbreviation: 'TEX' },
  { id: 'tor-mlb', name: 'Toronto Blue Jays', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/tor.png', primaryColor: '#134A8E', secondaryColor: '#1D2D5C', city: 'Toronto', abbreviation: 'TOR' },
  { id: 'was-mlb', name: 'Washington Nationals', leagueId: 'mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/wsh.png', primaryColor: '#AB0003', secondaryColor: '#14225A', city: 'Washington', abbreviation: 'WSH' },
];

export const MLS_TEAMS: Team[] = [
  { id: 'atl-utd', name: 'Atlanta United FC', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/18418.png', primaryColor: '#80000A', secondaryColor: '#221F1F', city: 'Atlanta', abbreviation: 'ATL' },
  { id: 'aus-fc', name: 'Austin FC', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/20906.png', primaryColor: '#00B140', secondaryColor: '#000000', city: 'Austin', abbreviation: 'ATX' },
  { id: 'cha-fc', name: 'Charlotte FC', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/21300.png', primaryColor: '#1A85C8', secondaryColor: '#000000', city: 'Charlotte', abbreviation: 'CLT' },
  { id: 'chi-fire', name: 'Chicago Fire FC', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/182.png', primaryColor: '#C8102E', secondaryColor: '#7CCDEF', city: 'Chicago', abbreviation: 'CHI' },
  { id: 'cin-fc', name: 'FC Cincinnati', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/18267.png', primaryColor: '#F05323', secondaryColor: '#263B80', city: 'Cincinnati', abbreviation: 'CIN' },
  { id: 'col-rapids', name: 'Colorado Rapids', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/184.png', primaryColor: '#862633', secondaryColor: '#8BB8E8', city: 'Commerce City', abbreviation: 'COL' },
  { id: 'cbus-crew', name: 'Columbus Crew', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/183.png', primaryColor: '#000000', secondaryColor: '#FFE667', city: 'Columbus', abbreviation: 'CLB' },
  { id: 'dc-utd', name: 'D.C. United', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/193.png', primaryColor: '#000000', secondaryColor: '#EF3E42', city: 'Washington', abbreviation: 'DC' },
  { id: 'dal-fc', name: 'FC Dallas', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/185.png', primaryColor: '#BF0D3E', secondaryColor: '#FFFFFF', city: 'Frisco', abbreviation: 'DAL' },
  { id: 'hou-dynamo', name: 'Houston Dynamo FC', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/6077.png', primaryColor: '#F68712', secondaryColor: '#101820', city: 'Houston', abbreviation: 'HOU' },
  { id: 'inter-mia', name: 'Inter Miami CF', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/20232.png', primaryColor: '#F5B5C8', secondaryColor: '#231F20', city: 'Fort Lauderdale', abbreviation: 'MIA' },
  { id: 'lafc', name: 'Los Angeles FC', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/18966.png', primaryColor: '#000000', secondaryColor: '#C39E6D', city: 'Los Angeles', abbreviation: 'LAFC' },
  { id: 'la-galaxy', name: 'LA Galaxy', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/187.png', primaryColor: '#00245D', secondaryColor: '#FFD200', city: 'Carson', abbreviation: 'LA' },
  { id: 'min-utd', name: 'Minnesota United FC', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/17362.png', primaryColor: '#8CD0F0', secondaryColor: '#231F20', city: 'Saint Paul', abbreviation: 'MIN' },
  { id: 'mtl-cf', name: 'CF Montréal', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9720.png', primaryColor: '#0033A1', secondaryColor: '#000000', city: 'Montreal', abbreviation: 'MTL' },
  { id: 'nsh-sc', name: 'Nashville SC', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/18986.png', primaryColor: '#ECE83A', secondaryColor: '#1F1646', city: 'Nashville', abbreviation: 'NSH' },
  { id: 'ne-rev', name: 'New England Revolution', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/189.png', primaryColor: '#0A2240', secondaryColor: '#CE0E2D', city: 'Foxborough', abbreviation: 'NE' },
  { id: 'nyc-fc', name: 'New York City FC', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/17606.png', primaryColor: '#6CACE4', secondaryColor: '#F15524', city: 'New York', abbreviation: 'NYC' },
  { id: 'ny-rb', name: 'New York Red Bulls', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/190.png', primaryColor: '#ED1E36', secondaryColor: '#FFCD00', city: 'Harrison', abbreviation: 'NYRB' },
  { id: 'orl-city', name: 'Orlando City SC', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/12011.png', primaryColor: '#633492', secondaryColor: '#FDE192', city: 'Orlando', abbreviation: 'ORL' },
  { id: 'phi-union', name: 'Philadelphia Union', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/10739.png', primaryColor: '#071B2C', secondaryColor: '#B18500', city: 'Chester', abbreviation: 'PHI' },
  { id: 'por-timbers', name: 'Portland Timbers', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9723.png', primaryColor: '#004812', secondaryColor: '#EBE72B', city: 'Portland', abbreviation: 'POR' },
  { id: 'rsl', name: 'Real Salt Lake', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/4771.png', primaryColor: '#B30838', secondaryColor: '#013A81', city: 'Sandy', abbreviation: 'RSL' },
  { id: 'sj-quakes', name: 'San Jose Earthquakes', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/191.png', primaryColor: '#0067B1', secondaryColor: '#000000', city: 'San Jose', abbreviation: 'SJ' },
  { id: 'sd-fc', name: 'San Diego FC', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/22529.png', primaryColor: '#00205B', secondaryColor: '#00AEEF', city: 'San Diego', abbreviation: 'SD' },
  { id: 'sea-sounders', name: 'Seattle Sounders FC', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9726.png', primaryColor: '#005695', secondaryColor: '#658D1B', city: 'Seattle', abbreviation: 'SEA' },
  { id: 'skc', name: 'Sporting Kansas City', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/186.png', primaryColor: '#002B5C', secondaryColor: '#91B0D5', city: 'Kansas City', abbreviation: 'SKC' },
  { id: 'stl-city', name: 'St. Louis City SC', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/21812.png', primaryColor: '#D2263C', secondaryColor: '#0F2044', city: 'St. Louis', abbreviation: 'STL' },
  { id: 'tor-fc', name: 'Toronto FC', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/7318.png', primaryColor: '#B81137', secondaryColor: '#455560', city: 'Toronto', abbreviation: 'TOR' },
  { id: 'van-whitecaps', name: 'Vancouver Whitecaps FC', leagueId: 'mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9727.png', primaryColor: '#00245E', secondaryColor: '#9DC2EA', city: 'Vancouver', abbreviation: 'VAN' },
];

export function getTeamsByLeague(leagueId: string): Team[] {
  switch (leagueId) {
    case 'nhl':
      return NHL_TEAMS;
    case 'nba':
      return NBA_TEAMS;
    case 'nfl':
      return NFL_TEAMS;
    case 'mlb':
      return MLB_TEAMS;
    case 'mls':
      return MLS_TEAMS;
    default:
      return [];
  }
}
