import { Game } from './types';

const NHL_LOGOS: Record<string, string> = {
  'Carolina Hurricanes': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4a/Carolina_Hurricanes.svg/200px-Carolina_Hurricanes.svg.png',
  'Chicago Blackhawks': 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/Chicago_Blackhawks_logo.svg/200px-Chicago_Blackhawks_logo.svg.png',
  'Philadelphia Flyers': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4a/Philadelphia_Flyers.svg/200px-Philadelphia_Flyers.svg.png',
  'Ottawa Senators': 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b2/Ottawa_Senators_2020-2021_logo.svg/200px-Ottawa_Senators_2020-2021_logo.svg.png',
  'Pittsburgh Penguins': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c0/Pittsburgh_Penguins_logo_%282016%29.svg/200px-Pittsburgh_Penguins_logo_%282016%29.svg.png',
  'Vegas Golden Knights': 'https://upload.wikimedia.org/wikipedia/en/thumb/a/ac/Vegas_Golden_Knights_logo.svg/200px-Vegas_Golden_Knights_logo.svg.png',
  'Anaheim Ducks': 'https://upload.wikimedia.org/wikipedia/en/thumb/7/72/Anaheim_Ducks.svg/200px-Anaheim_Ducks.svg.png',
  'Dallas Stars': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/Dallas_Stars_logo_%282013%29.svg/200px-Dallas_Stars_logo_%282013%29.svg.png',
  'Washington Capitals': 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Washington_Capitals.svg/200px-Washington_Capitals.svg.png',
  'Tampa Bay Lightning': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/92/Tampa_Bay_Lightning_Logo_2011.svg/200px-Tampa_Bay_Lightning_Logo_2011.svg.png',
  'Vancouver Canucks': 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3a/Vancouver_Canucks_logo.svg/200px-Vancouver_Canucks_logo.svg.png',
  'New Jersey Devils': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9f/New_Jersey_Devils_logo.svg/200px-New_Jersey_Devils_logo.svg.png',
  'Edmonton Oilers': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4d/Logo_Edmonton_Oilers.svg/200px-Logo_Edmonton_Oilers.svg.png',
  'Calgary Flames': 'https://upload.wikimedia.org/wikipedia/en/thumb/6/61/Calgary_Flames_logo.svg/200px-Calgary_Flames_logo.svg.png',
  'Toronto Maple Leafs': 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b6/Toronto_Maple_Leafs_2016_logo.svg/200px-Toronto_Maple_Leafs_2016_logo.svg.png',
  'Nashville Predators': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9c/Nashville_Predators_Logo_%282011%29.svg/200px-Nashville_Predators_Logo_%282011%29.svg.png',
  'Columbus Blue Jackets': 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5d/Columbus_Blue_Jackets_logo.svg/200px-Columbus_Blue_Jackets_logo.svg.png',
  'New York Islanders': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/42/Logo_New_York_Islanders.svg/200px-Logo_New_York_Islanders.svg.png',
  'Los Angeles Kings': 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e7/Los_Angeles_Kings_logo.svg/200px-Los_Angeles_Kings_logo.svg.png',
  'St. Louis Blues': 'https://upload.wikimedia.org/wikipedia/en/thumb/e/ed/St._Louis_Blues_logo.svg/200px-St._Louis_Blues_logo.svg.png',
  'Montreal Canadiens': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Montreal_Canadiens.svg/200px-Montreal_Canadiens.svg.png',
  'New York Rangers': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/New_York_Rangers.svg/200px-New_York_Rangers.svg.png',
  'Colorado Avalanche': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/45/Colorado_Avalanche_logo.svg/200px-Colorado_Avalanche_logo.svg.png',
  'San Jose Sharks': 'https://upload.wikimedia.org/wikipedia/en/thumb/3/37/SanJoseSharksLogo.svg/200px-SanJoseSharksLogo.svg.png',
  'Utah Mammoth': 'https://a.espncdn.com/i/teamlogos/nhl/500/uta.png',
  'Utah Hockey Club': 'https://a.espncdn.com/i/teamlogos/nhl/500/uta.png',
  'Winnipeg Jets': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/93/Winnipeg_Jets_Logo_2011.svg/200px-Winnipeg_Jets_Logo_2011.svg.png',
  'Buffalo Sabres': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Buffalo_Sabres_Logo.svg/200px-Buffalo_Sabres_Logo.svg.png',
  'Boston Bruins': 'https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Boston_Bruins.svg/200px-Boston_Bruins.svg.png',
  'Detroit Red Wings': 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e0/Detroit_Red_Wings_logo.svg/200px-Detroit_Red_Wings_logo.svg.png',
  'Seattle Kraken': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/48/Seattle_Kraken_official_logo.svg/200px-Seattle_Kraken_official_logo.svg.png',
  'Minnesota Wild': 'https://upload.wikimedia.org/wikipedia/en/thumb/1/1b/Minnesota_Wild.svg/200px-Minnesota_Wild.svg.png',
};

function getOpponentLogo(opponent: string): string | undefined {
  const teamName = opponent.replace(/^vs\s+/, '');
  return NHL_LOGOS[teamName];
}

// Lazy-load the schedule data to avoid Hermes engine crash on macOS Catalyst
// Large arrays evaluated at module init time can trigger EXC_BAD_ACCESS
let _cachedSchedule: Game[] | null = null;

function getScheduleData(): Game[] {
  if (_cachedSchedule) return _cachedSchedule;
  
  try {
    _cachedSchedule = [
  {
    id: 'p1',
    date: 'Sep 29, 2025',
    month: 'Sep',
    day: '29',
    opponent: 'vs Carolina Hurricanes',
    opponentLogo: getOpponentLogo('vs Carolina Hurricanes'),
    time: '6:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Preseason',
    gameNumber: 'PS 1',
    dateTimeISO: '2025-09-29T22:00:00Z',
  },
  {
    id: 'p2',
    date: 'Oct 04, 2025',
    month: 'Oct',
    day: '04',
    opponent: 'vs Tampa Bay Lightning',
    opponentLogo: getOpponentLogo('vs Tampa Bay Lightning'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Preseason',
    gameNumber: 'PS 2',
    dateTimeISO: '2025-10-04T23:00:00Z',
  },
  {
    id: '1',
    date: 'Oct 07, 2025',
    month: 'Oct',
    day: '07',
    opponent: 'vs Chicago Blackhawks',
    opponentLogo: getOpponentLogo('vs Chicago Blackhawks'),
    time: '5:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '1',
    dateTimeISO: '2025-10-07T21:00:00Z',
  },
  {
    id: '2',
    date: 'Oct 09, 2025',
    month: 'Oct',
    day: '09',
    opponent: 'vs Philadelphia Flyers',
    opponentLogo: getOpponentLogo('vs Philadelphia Flyers'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '2',
    dateTimeISO: '2025-10-09T23:00:00Z',
  },
  {
    id: '3',
    date: 'Oct 11, 2025',
    month: 'Oct',
    day: '11',
    opponent: 'vs Ottawa Senators',
    opponentLogo: getOpponentLogo('vs Ottawa Senators'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '3',
    dateTimeISO: '2025-10-11T23:00:00Z',
  },
  {
    id: '4',
    date: 'Oct 23, 2025',
    month: 'Oct',
    day: '23',
    opponent: 'vs Pittsburgh Penguins',
    opponentLogo: getOpponentLogo('vs Pittsburgh Penguins'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '4',
    dateTimeISO: '2025-10-23T23:00:00Z',
  },
  {
    id: '5',
    date: 'Oct 25, 2025',
    month: 'Oct',
    day: '25',
    opponent: 'vs Vegas Golden Knights',
    opponentLogo: getOpponentLogo('vs Vegas Golden Knights'),
    time: '6:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '5',
    dateTimeISO: '2025-10-25T22:00:00Z',
  },
  {
    id: '6',
    date: 'Oct 28, 2025',
    month: 'Oct',
    day: '28',
    opponent: 'vs Anaheim Ducks',
    opponentLogo: getOpponentLogo('vs Anaheim Ducks'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '6',
    dateTimeISO: '2025-10-28T23:00:00Z',
  },
  {
    id: '7',
    date: 'Nov 01, 2025',
    month: 'Nov',
    day: '01',
    opponent: 'vs Dallas Stars',
    opponentLogo: getOpponentLogo('vs Dallas Stars'),
    time: '6:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '7',
    dateTimeISO: '2025-11-01T22:00:00Z',
  },
  {
    id: '8',
    date: 'Nov 13, 2025',
    month: 'Nov',
    day: '13',
    opponent: 'vs Washington Capitals',
    opponentLogo: getOpponentLogo('vs Washington Capitals'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '8',
    dateTimeISO: '2025-11-14T00:00:00Z',
  },
  {
    id: '9',
    date: 'Nov 15, 2025',
    month: 'Nov',
    day: '15',
    opponent: 'vs Tampa Bay Lightning',
    opponentLogo: getOpponentLogo('vs Tampa Bay Lightning'),
    time: '6:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '9',
    dateTimeISO: '2025-11-15T23:00:00Z',
  },
  {
    id: '10',
    date: 'Nov 17, 2025',
    month: 'Nov',
    day: '17',
    opponent: 'vs Vancouver Canucks',
    opponentLogo: getOpponentLogo('vs Vancouver Canucks'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '10',
    dateTimeISO: '2025-11-18T00:00:00Z',
  },
  {
    id: '11',
    date: 'Nov 20, 2025',
    month: 'Nov',
    day: '20',
    opponent: 'vs New Jersey Devils',
    opponentLogo: getOpponentLogo('vs New Jersey Devils'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '11',
    dateTimeISO: '2025-11-21T00:00:00Z',
  },
  {
    id: '12',
    date: 'Nov 22, 2025',
    month: 'Nov',
    day: '22',
    opponent: 'vs Edmonton Oilers',
    opponentLogo: getOpponentLogo('vs Edmonton Oilers'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '12',
    dateTimeISO: '2025-11-23T00:00:00Z',
  },
  {
    id: '13',
    date: 'Nov 26, 2025',
    month: 'Nov',
    day: '26',
    opponent: 'vs Philadelphia Flyers',
    opponentLogo: getOpponentLogo('vs Philadelphia Flyers'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '13',
    dateTimeISO: '2025-11-27T00:00:00Z',
  },
  {
    id: '14',
    date: 'Nov 28, 2025',
    month: 'Nov',
    day: '28',
    opponent: 'vs Calgary Flames',
    opponentLogo: getOpponentLogo('vs Calgary Flames'),
    time: '4:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '14',
    dateTimeISO: '2025-11-28T21:00:00Z',
  },
  {
    id: '15',
    date: 'Dec 02, 2025',
    month: 'Dec',
    day: '02',
    opponent: 'vs Toronto Maple Leafs',
    opponentLogo: getOpponentLogo('vs Toronto Maple Leafs'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '15',
    dateTimeISO: '2025-12-03T00:00:00Z',
  },
  {
    id: '16',
    date: 'Dec 04, 2025',
    month: 'Dec',
    day: '04',
    opponent: 'vs Nashville Predators',
    opponentLogo: getOpponentLogo('vs Nashville Predators'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '16',
    dateTimeISO: '2025-12-05T00:00:00Z',
  },
  {
    id: '17',
    date: 'Dec 06, 2025',
    month: 'Dec',
    day: '06',
    opponent: 'vs Columbus Blue Jackets',
    opponentLogo: getOpponentLogo('vs Columbus Blue Jackets'),
    time: '3:30 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '17',
    dateTimeISO: '2025-12-06T20:30:00Z',
  },
  {
    id: '18',
    date: 'Dec 07, 2025',
    month: 'Dec',
    day: '07',
    opponent: 'vs New York Islanders',
    opponentLogo: getOpponentLogo('vs New York Islanders'),
    time: '5:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '18',
    dateTimeISO: '2025-12-07T22:00:00Z',
  },
  {
    id: '19',
    date: 'Dec 17, 2025',
    month: 'Dec',
    day: '17',
    opponent: 'vs Los Angeles Kings',
    opponentLogo: getOpponentLogo('vs Los Angeles Kings'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '19',
    dateTimeISO: '2025-12-18T00:00:00Z',
  },
  {
    id: '20',
    date: 'Dec 19, 2025',
    month: 'Dec',
    day: '19',
    opponent: 'vs Carolina Hurricanes',
    opponentLogo: getOpponentLogo('vs Carolina Hurricanes'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '20',
    dateTimeISO: '2025-12-20T00:00:00Z',
  },
  {
    id: '21',
    date: 'Dec 20, 2025',
    month: 'Dec',
    day: '20',
    opponent: 'vs St. Louis Blues',
    opponentLogo: getOpponentLogo('vs St. Louis Blues'),
    time: '6:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '21',
    dateTimeISO: '2025-12-20T23:00:00Z',
  },
  {
    id: '22',
    date: 'Dec 27, 2025',
    month: 'Dec',
    day: '27',
    opponent: 'vs Tampa Bay Lightning',
    opponentLogo: getOpponentLogo('vs Tampa Bay Lightning'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '22',
    dateTimeISO: '2025-12-28T00:00:00Z',
  },
  {
    id: '23',
    date: 'Dec 29, 2025',
    month: 'Dec',
    day: '29',
    opponent: 'vs Washington Capitals',
    opponentLogo: getOpponentLogo('vs Washington Capitals'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '23',
    dateTimeISO: '2025-12-30T00:00:00Z',
  },
  {
    id: '24',
    date: 'Dec 30, 2025',
    month: 'Dec',
    day: '30',
    opponent: 'vs Montreal Canadiens',
    opponentLogo: getOpponentLogo('vs Montreal Canadiens'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '24',
    dateTimeISO: '2025-12-31T00:00:00Z',
  },
  {
    id: '25',
    date: 'Jan 04, 2026',
    month: 'Jan',
    day: '04',
    opponent: 'vs Colorado Avalanche',
    opponentLogo: getOpponentLogo('vs Colorado Avalanche'),
    time: '5:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '25',
    dateTimeISO: '2026-01-04T22:00:00Z',
  },
  {
    id: '26',
    date: 'Jan 19, 2026',
    month: 'Jan',
    day: '19',
    opponent: 'vs San Jose Sharks',
    opponentLogo: getOpponentLogo('vs San Jose Sharks'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '26',
    dateTimeISO: '2026-01-20T00:00:00Z',
  },
  {
    id: '27',
    date: 'Jan 27, 2026',
    month: 'Jan',
    day: '27',
    opponent: 'vs Utah Mammoth',
    opponentLogo: getOpponentLogo('vs Utah Mammoth'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '27',
    dateTimeISO: '2026-01-28T00:00:00Z',
  },
  {
    id: '28',
    date: 'Jan 31, 2026',
    month: 'Jan',
    day: '31',
    opponent: 'vs Winnipeg Jets',
    opponentLogo: getOpponentLogo('vs Winnipeg Jets'),
    time: '4:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '28',
    dateTimeISO: '2026-01-31T21:00:00Z',
  },
  {
    id: '29',
    date: 'Feb 02, 2026',
    month: 'Feb',
    day: '02',
    opponent: 'vs Buffalo Sabres',
    opponentLogo: getOpponentLogo('vs Buffalo Sabres'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '29',
    dateTimeISO: '2026-02-03T00:00:00Z',
  },
  {
    id: '30',
    date: 'Feb 04, 2026',
    month: 'Feb',
    day: '04',
    opponent: 'vs Boston Bruins',
    opponentLogo: getOpponentLogo('vs Boston Bruins'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '30',
    dateTimeISO: '2026-02-05T00:00:00Z',
  },
  {
    id: '31',
    date: 'Feb 26, 2026',
    month: 'Feb',
    day: '26',
    opponent: 'vs Toronto Maple Leafs',
    opponentLogo: getOpponentLogo('vs Toronto Maple Leafs'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '31',
    dateTimeISO: '2026-02-27T00:00:00Z',
  },
  {
    id: '32',
    date: 'Feb 27, 2026',
    month: 'Feb',
    day: '27',
    opponent: 'vs Buffalo Sabres',
    opponentLogo: getOpponentLogo('vs Buffalo Sabres'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '32',
    dateTimeISO: '2026-02-28T00:00:00Z',
  },
  {
    id: '33',
    date: 'Mar 10, 2026',
    month: 'Mar',
    day: '10',
    opponent: 'vs Detroit Red Wings',
    opponentLogo: getOpponentLogo('vs Detroit Red Wings'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '33',
    dateTimeISO: '2026-03-11T00:00:00Z',
  },
  {
    id: '34',
    date: 'Mar 12, 2026',
    month: 'Mar',
    day: '12',
    opponent: 'vs Columbus Blue Jackets',
    opponentLogo: getOpponentLogo('vs Columbus Blue Jackets'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '34',
    dateTimeISO: '2026-03-13T00:00:00Z',
  },
  {
    id: '35',
    date: 'Mar 24, 2026',
    month: 'Mar',
    day: '24',
    opponent: 'vs Seattle Kraken',
    opponentLogo: getOpponentLogo('vs Seattle Kraken'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '35',
    dateTimeISO: '2026-03-24T23:00:00Z',
  },
  {
    id: '36',
    date: 'Mar 26, 2026',
    month: 'Mar',
    day: '26',
    opponent: 'vs Minnesota Wild',
    opponentLogo: getOpponentLogo('vs Minnesota Wild'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '36',
    dateTimeISO: '2026-03-26T23:00:00Z',
  },
  {
    id: '37',
    date: 'Mar 31, 2026',
    month: 'Mar',
    day: '31',
    opponent: 'vs Ottawa Senators',
    opponentLogo: getOpponentLogo('vs Ottawa Senators'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '37',
    dateTimeISO: '2026-03-31T23:00:00Z',
  },
  {
    id: '38',
    date: 'Apr 02, 2026',
    month: 'Apr',
    day: '02',
    opponent: 'vs Boston Bruins',
    opponentLogo: getOpponentLogo('vs Boston Bruins'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '38',
    dateTimeISO: '2026-04-02T23:00:00Z',
  },
  {
    id: '39',
    date: 'Apr 13, 2026',
    month: 'Apr',
    day: '13',
    opponent: 'vs New York Rangers',
    opponentLogo: getOpponentLogo('vs New York Rangers'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '39',
    dateTimeISO: '2026-04-13T23:00:00Z',
  },
  {
    id: '40',
    date: 'Apr 15, 2026',
    month: 'Apr',
    day: '15',
    opponent: 'vs Detroit Red Wings',
    opponentLogo: getOpponentLogo('vs Detroit Red Wings'),
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Regular',
    gameNumber: '40',
    dateTimeISO: '2026-04-15T23:00:00Z',
  },
    ];
  } catch (e) {
    console.error('[panthersSchedule] Failed to initialize schedule:', e);
    _cachedSchedule = [];
  }
  
  return _cachedSchedule;
}

// Export as a getter proxy so it lazily loads on first access
export const PANTHERS_20252026_SCHEDULE: Game[] = new Proxy([] as Game[], {
  get(target, prop) {
    const data = getScheduleData();
    if (prop === 'length') return data.length;
    if (typeof prop === 'string' && !isNaN(Number(prop))) {
      return data[Number(prop)];
    }
    if (prop === Symbol.iterator) {
      return function* () { yield* data; };
    }
    // Handle array methods
    const value = (data as any)[prop];
    if (typeof value === 'function') {
      return value.bind(data);
    }
    return value;
  },
});

export default PANTHERS_20252026_SCHEDULE;
