name = "spm-api"
account_id = "243fe5a25835bb0c260e39a58ee47cb4"
compatibility_date = "2026-02-19"


# Specify the entry point for the worker

main = "worker.ts"

[vars]
SPORTSDATAIO_API_KEY = "9b42211a91c1440795cd6217baa9e334"
